### ISSUE TITLE
Avoid synchronizing repo if it has already been pulled

### ISSUE THREAD

**Issue by kevinwolfdev** [pulumi/actions-pulumify#13]
Hi! I am running through some errors trying to use this action. The reason its because it is trying to init and fetch an already fetched repo with `actions/checkout@v1` and outputting the following error: `fatal: remote origin already exists.`.

## Suggested solutions

1. Specify on the readme that `actions/checkout@v1` should be run first and dont try to fetch the repo within the action (this is kind of standard for other actions)
2. Add a `SKIP_FETCH` flag if the user wants to skip the fetching.

Any thoughts? Happy to put a PR if needed :).

**Comment by chrsmith** [comment]
Hey @kevinwolfdev , I'm happy to update the `README.md` or the `pulumify` script to make things less error prone and/or easier to use. Would you mind sharing your GitHub Actions workflow file (that runs `actions/checkout@v1`) as an example, since presumably we'd want something like that to "just work". As well as, I guess, a GitHub Actions workflow that doesn't require `actions/checkout@v1`, right?

It looks like we are cloning the GitHub repo [here](https://github.com/pulumi/actions-pulumify/blob/master/infra/pulumify#L73lL77). So it looks like we could easy skip the `git init` step if we knew that the repo was already synced... can you think of the best way to do that? Does just checking for the existence of a `.git/` folder seem robust enough in practice?

**Comment by kevinwolfdev** [comment]
Hi, @chrsmith, thanks for your response. The workflow file I'm using is this one:

```yaml
name: 🚀 Deploy Isolated environment

on: pull_request

jobs:
  deploy:
    name: Deploy Isolated environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: wsrun -t -r -m -c build
      - name: Lint
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: wsrun -m -c lint
      - name: Test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: wsrun -m -c test
      - name: Deploy preview
        uses: docker://joeduffy/pulumify
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMIFY_ROOT: path/to/my/static/website
      - name: Pulumi preview
        uses: docker://pulumi/actions
        with:
          args: preview
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: pr
          PULUMI_ROOT: infra
```

However, I was checking other GitHub actions on the marketplace, and almost all of them recommends to run `actions/checkout` first:

- [Yarn action](https://github.com/marketplace/actions/github-action-for-yarn)
- [zeit-now-deployment](https://github.com/marketplace/actions/zeit-now-deployment)
- [Google Cloud](https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml)
- And even the official Pulumi actions ([push](https://github.com/pulumi/actions/blob/master/examples/.github/workflows/push.yml#L11) and [pull_request](https://github.com/pulumi/actions/blob/master/examples/.github/workflows/pull_request.yml#L9))

My recommendation will be to fully remove the git checkout step, on this way, the `pulumify` action will be more scoped and will have a single responsibility (checking out files its out of it scope).

What do you think?
